rol:
  class: sfPropelORMRouteCollection
  options:
    model:                rol
    module:               AbmRol
    prefix_path:          /AbmRol
    column:               id
    with_wildcard_routes: true

usuario:
  class: sfPropelORMRouteCollection
  options:
    model:                usuario
    module:               AbmUsuario
    prefix_path:          /AbmUsuario
    column:               id
    with_wildcard_routes: true

reparticion:
  class: sfPropelORMRouteCollection
  options:
    model:                reparticion
    module:               AbmReparticion
    prefix_path:          /AbmReparticion
    column:               id
    with_wildcard_routes: true

estado_civil:
  class: sfPropelORMRouteCollection
  options:
    model:                estadoCivil
    module:               AbmEstadoCivil
    prefix_path:          /AbmEstadoCivil
    column:               id
    with_wildcard_routes: true

afiliado:
  class: sfPropelORMRouteCollection
  options:
    model:                afiliado
    module:               AbmAfiliado
    prefix_path:          /AbmAfiliado
    column:               id
    with_wildcard_routes: true

especialidad:
  class: sfPropelORMRouteCollection
  options:
    model:                especialidad
    module:               AbmEspecialidad
    prefix_path:          /AbmEspecialidad
    column:               id
    with_wildcard_routes: true

sexo:
  class: sfPropelORMRouteCollection
  options:
    model:                sexo
    module:               AbmSexo
    prefix_path:          /AbmSexo
    column:               id
    with_wildcard_routes: true

tipo_doc:
  class: sfPropelORMRouteCollection
  options:
    model:                tipoDoc
    module:               AbmTipoDoc
    prefix_path:          /AbmTipoDoc
    column:               id
    with_wildcard_routes: true

centro_atencion:
  class: sfPropelORMRouteCollection
  options:
    model:                centroAtencion
    module:               AbmCentroAtencion
    prefix_path:          /AbmCentroAtencion
    column:               id
    with_wildcard_routes: true

localidad:
  class: sfPropelORMRouteCollection
  options:
    model:                localidad
    module:               Abmlocalidad
    prefix_path:          /Abmlocalidad
    column:               id
    with_wildcard_routes: true

prestador:
  class: sfPropelORMRouteCollection
  options:
    model:                prestador
    module:               AbmPrestador
    prefix_path:          /AbmPrestador
    column:               id
    with_wildcard_routes: true

plan:
  class: sfPropelORMRouteCollection
  options:
    model:                plan
    module:               AbmPlan
    prefix_path:          /AbmPlan
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: login, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
